version: 2
jobs:
  build:
    parallelism: 1
    docker:
      - image: circleci/elixir:1.11.3-node
        environment:
          MIX_ENV: test
      - image: circleci/postgres:13.1-postgis-ram
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: carrier_pigeon_test
          POSTGRES_PASSWORD:
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Download dependencies
          command: |
          mix local.hex --force
          mix local.rebar --force
          mix deps.get
      - run:
          name: Compile
          command: mix compile
      - restore_cache:
          keys:
            - v1-mix-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
            - v1-mix-cache-{{ .Branch }}
            - v1-mix-cache
      - restore_cache:
          keys:
            - v1-build-cache-{{ .Branch }}
            - v1-build-cache
      - save_cache:
          key: v1-mix-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
          paths: ["deps"]
      - save_cache:
          key: v1-mix-cache-{{ .Branch }}
          paths: ["deps"]
      - save_cache:
          key: v1-mix-cache
          paths: ["deps"]
      - save_cache:
          key: v1-build-cache-{{ .Branch }}
          paths: ["_build"]
      - save_cache:
          key: v1-build-cache
          paths: ["_build"]
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Test
          command: mix test